from enum import IntEnum

class STATUS(IntEnum):
    TX_SYNCED = 209
    TX_NEED_SYNC = 208
    TRANSACTION_INTERNAL = 207
    TRANSACTION_ONCHAIN = 203
    TRANSACTION_OFFCHAIN = 202
    TRANSACTION_WITHDRAW = 201
    TRANSACTION_DEPOSIT = 200
    UNLOCKED = 51
    TRANSFER = 50
    SUBCRIPTION = 49
    BOX_OPENING = 17
    BOX_OPENED = 16
    UPGRADE_LAND = 15
    NFT_REQUEST_MINT_TX_CONFIRM_WAIT = 11
    NFT_REQUEST_MINT_TX_SUBMIT_WAIT = 10

    TX_CONFIRM_WAIT = 9
    TX_SUBMIT_WAIT = 8
    
    NFT_MINT_CID_WAIT = 7
    NFT_REQUEST_MINT_CID_WAIT = 6

    NFT_REQUEST_MINT_DAPP_WAIT = 5 #same as on request claim
    
    FORWARD = 4
    TX_SUCCESS = 3
    NORMAL = 1
    TX_PENDING = GAMESERVER_REPONSE_SUCCESS = QUEUE = 0
    INPUT_INVALID = -1
    TX_FAILED = -3

    NFT_REQUEST_MINT_DAPP_CANCELED = -5 #TODO: callback gameserver
    NFT_REQUEST_MINT_CID_FAILED = -6 #TODO: recovery needed
    NFT_MINT_CID_FAILED = -7 #TODO: recovery needed

    TX_SUBMIT_FAILED = -8
    TX_CONFIRM_FAILED = -9

    NFT_MINT_FAILED = -10 #TODO: callback gameserver
    NFT_REQUEST_MINT_FAILED = -11 #TODO: callback gameserver
    WAIT_MINT_CID_TIMEOUT = -12
    UPGRADE_LAND_FAILED = -13 #TODO: callback gameserver
    WAIT_BURN_BOX_TIMEOUT = -14

    RESP_WALLET_EXCEEDS_ALLOWANCE = -20
    RESP_WALLET_REWARD_OVERBALANCE = -21

    BURNED = -50
    LOCKED = -51
    SELL = -100    
    UNAUTHORIZED = -401    
    INPUT_SOMETHING_WRONG = -500
    HOTWALLET_TX_PENDING = -501

    TX_SYNC_NONE = -999
     
    BOX_NOT_OPEN = TX_SYNC_NONE
    
    RESP_WALLET_SUSPENDED = RESP_INPUT_INVALID = RESP_HOTWALLET_OVERBALANCE = RESP_HOTWALLET_REQUEST_WITHDRAW_DUPLICATE = RESP_NFT_MINT_DUPLICATE = INPUT_INVALID
    RESP_FORWARD = FORWARD
    RESP_NORMAL = NORMAL
    RESP_INPUT_SOMETHING_WRONG = INPUT_SOMETHING_WRONG
    RESP_HOTWALLET_TX_PENDING = HOTWALLET_TX_PENDING
    RESP_QUEUE = QUEUE
    RESP_VALIDATION_FAILED = RESP_INPUT_INVALID